name: pass_tool
description: Flutter Pass Tool Project
publish_to: 'none'
version: 1.0.020125+1210
environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  crypto: ^3.0.3
  libac_dart:
    hosted: https://git.zontreck.com/api/packages/AriasCreations/pub/
    version: ^1.4.012225+0413
  libacflutter:
    hosted: https://git.zontreck.com/api/packages/AriasCreations/pub/
    version: ^1.0.13125+0358
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
flutter:
  uses-material-design: true

